### ISSUE TITLE
[PPO, CUDA OOM] when running the trlx_gptj_text_summarization.py

### ISSUE THREAD

**Issue by JudeLee19** [CarperAI/trlx#266]
### 🐛 Describe the bug

Hello.

I'm following examples/summarize_rlhf experiment and I've done until the step that training the reward model without any problem.

However, in PPO training step, when I run,

"accelerate launch --config_file configs/default_accelerate_config.yaml trlx_gptj_text_summarization.py"

it produces OutOfMemoryError: CUDA out of memory.

**And the error is occurred in "rw_model.load_state_dict(torch.load(REWARD_CHECKPOINT_PATH))" line.**

<img width="866" alt="image" src="https://user-images.githubusercontent.com/6652613/216515403-74dd4903-cf92-46d7-99e3-deb61a93be42.png">

**I've tried with A100 8 GPUs and at the error line reward models from 8 processes are loaded in GPU:0, and produce an OOM error.**
<img width="806" alt="image" src="https://user-images.githubusercontent.com/6652613/216515665-ddb010b2-07ae-4e62-8501-d1f9393b4a2b.png">

I attached "default_acclerate_config.yaml" for reference. Thank you.

```
command_file: null
commands: null
compute_environment: LOCAL_MACHINE
deepspeed_config:
  deepspeed_hostfile: localhost slots=8
  deepspeed_config_file: configs/ds_config_trlx_gptj_summarize.json
  zero3_init_flag: false
distributed_type: DEEPSPEED
downcast_bf16: 'no'
dynamo_backend: 'NO'
fsdp_config: {}
gpu_ids: null
machine_rank: 0
main_process_ip: null
main_process_port: 8855
main_training_function: main
megatron_lm_config: {}
mixed_precision: 'no'
num_machines: 1
num_processes: 8
rdzv_backend: static
same_network: true
tpu_name: null
tpu_zone: null
use_cpu: false

```

### Which trlX version are you using?

trlx==0.4.0

### Additional system and package information

3.8 (Ubuntu 18.04)

**Comment by LouisCastricato** [comment]
Thanks. @PhungVanDuy did you experience this error?

**Comment by PhungVanDuy** [comment]
> Thanks. @PhungVanDuy did you experience this error?

I never faced this error before, but I am re-running it to check with the newest version.

**Comment by PhungVanDuy** [comment]
I just re-run with the newest trlx version it still works fine. 
![image](https://user-images.githubusercontent.com/28798474/216613932-3b3b1b1f-a203-4594-a02f-b64ccce3f271.png)

by default, we set cuda:1 for the reward model maybe you made some changes to cuda:0 and overlap with ppo model.

**Comment by microsoft-fevieira** [comment]
Any updates here? I am also facing this OOM issue. What are runtime requirements for this experiment?



  File "/home/aiscuser/.local/lib/python3.8/site-packages/trlx/trlx.py", line 109, in train
    trainer.learn()
  File "/home/aiscuser/.local/lib/python3.8/site-packages/trlx/trainer/accelerate_base_trainer.py", line 454, in learn
    self.accelerator.backward(loss)
  File "/home/aiscuser/.local/lib/python3.8/site-packages/accelerate/accelerator.py", line 1310, in backward
    self.deepspeed_engine_wrapped.backward(loss, **kwargs)
  File "/home/aiscuser/.local/lib/python3.8/site-packages/accelerate/utils/deepspeed.py", line 156, in backward
    self.engine.backward(loss)
  File "/home/aiscuser/.local/lib/python3.8/site-packages/deepspeed/utils/nvtx.py", line 11, in wrapped_fn
    return func(*args, **kwargs)
  File "/home/aiscuser/.local/lib/python3.8/site-packages/deepspeed/runtime/engine.py", line 1799, in backward
    self.optimizer.backward(loss, retain_graph=retain_graph)
  File "/home/aiscuser/.local/lib/python3.8/site-packages/deepspeed/runtime/zero/stage_1_and_2.py", line 1936, in backward
    buf_0 = torch.empty(int(self.reduce_bucket_size),
RuntimeError: CUDA out of memory. Tried to allocate 954.00 MiB (GPU 0; 31.75 GiB total capacity; 29.99 GiB already allocated; 445.94 MiB free; 30.27 GiB reserved in total by PyTorch) If reserved memory is >> allocated memory try setting max_split_size_mb to avoid fragmentation.  See documentation for Memory Management and PYTORCH_CUDA_ALLOC_CONF
╭───────────────────── Traceback (most recent call last) ──────────────────────╮
│ /scratch/amlt_code/examples/trlx/train_rl_gptj_text_summarization.py:126 in  │
│ <module>                                                                     │
│                                                                              │
│   123 │   config.train.checkpoint_dir = output_dir                           │
│   124 │   config.train.logging_dir = output_dir                              │
│   125 │                                                                      │
│ ❱ 126 │   trainer = trlx.train(                                              │
│   127 │   │   config.model.model_path,                                       │
│   128 │   │   reward_fn=reward_fn,                                           │
│   129 │   │   prompts=train_prompts,                                         │
│                                                                              │
│ /home/aiscuser/.local/lib/python3.8/site-packages/trlx/trlx.py:109 in train  │
│                                                                              │
│   106 │   else:                                                              │
│   107 │   │   raise ValueError(f"Either {dataset=} or {reward_fn=} should be │
│   108 │                                                                      │
│ ❱ 109 │   trainer.learn()                                                    │
│   110 │   return trainer                                                     │
│   111                                                                        │
│                                                                              │
│ /home/aiscuser/.local/lib/python3.8/site-packages/trlx/trainer/accelerate_ba │
│ se_trainer.py:454 in learn                                                   │
│                                                                              │
│   451 │   │   │   │   │   loss, stats = self.loss(batch)                     │
│   452 │   │   │   │   │   forward_time = time() - forward_time               │
│   453 │   │   │   │   │   backward_time = time()                             │
│ ❱ 454 │   │   │   │   │   self.accelerator.backward(loss)                    │
│   455 │   │   │   │   │   backward_time = time() - backward_time             │
│   456 │   │   │   │   │                                                      │
│   457 │   │   │   │   │   self.opt.step()                                    │
│                                                                              │
│ /home/aiscuser/.local/lib/python3.8/site-packages/accelerate/accelerator.py: │
│ 1310 in backward                                                             │
│                                                                              │
│   1307 │   │   │   # deepspeed handles loss scaling by gradient_accumulation │
│   1308 │   │   │   loss = loss / self.gradient_accumulation_steps            │
│   1309 │   │   if self.distributed_type == DistributedType.DEEPSPEED:        │
│ ❱ 1310 │   │   │   self.deepspeed_engine_wrapped.backward(loss, **kwargs)    │
│   1311 │   │   elif self.distributed_type == DistributedType.MEGATRON_LM:    │
│   1312 │   │   │   return                                                    │
│   1313 │   │   elif self.scaler is not None:                                 │
│                                                                              │
│ /home/aiscuser/.local/lib/python3.8/site-packages/accelerate/utils/deepspeed │
│ .py:156 in backward                                                          │
│                                                                              │
│   153 │                                                                      │
│   154 │   def backward(self, loss):                                          │
│   155 │   │   # runs backpropagation and handles mixed precision             │
│ ❱ 156 │   │   self.engine.backward(loss)                                     │
│   157 │   │                                                                  │
│   158 │   │   # deepspeed `engine.step` performs following operations:       │
│   159 │   │   # gradient accumulation check                                  │
│                                                                              │
│ /home/aiscuser/.local/lib/python3.8/site-packages/deepspeed/utils/nvtx.py:11 │
│ in wrapped_fn                                                                │
│                                                                              │
│    8 │   │                                                                   │
│    9 │   │   def wrapped_fn(*args, **kwargs):                                │
│   10 │   │   │   with torch.cuda.nvtx.range(func.__qualname__):              │
│ ❱ 11 │   │   │   │   return func(*args, **kwargs)                            │
│   12 │   │                                                                   │
│   13 │   │   return wrapped_fn                                               │
│   14 │   else:                                                               │
│                                                                              │
│ /home/aiscuser/.local/lib/python3.8/site-packages/deepspeed/runtime/engine.p │
│ y:1799 in backward                                                           │
│                                                                              │
│   1796 │   │   if self.zero_optimization():                                  │
│   1797 │   │   │   self.optimizer.is_gradient_accumulation_boundary = self.i │
│   1798 │   │   │   )                                                         │
│ ❱ 1799 │   │   │   self.optimizer.backward(loss, retain_graph=retain_graph)  │
│   1800 │   │   elif self.amp_enabled():                                      │
│   1801 │   │   │   # AMP requires delaying unscale when inside gradient accu │
│   1802 │   │   │   # https://nvidia.github.io/apex/advanced.html#gradient-ac │
│                                                                              │
│ /home/aiscuser/.local/lib/python3.8/site-packages/deepspeed/runtime/zero/sta │
│ ge_1_and_2.py:1936 in backward                                               │
│                                                                              │
│   1933 │   │                                                                 │
│   1934 │   │   if self.contiguous_gradients:                                 │
│   1935 │   │   │   self.ipg_buffer = []                                      │
│ ❱ 1936 │   │   │   buf_0 = torch.empty(int(self.reduce_bucket_size),         │
│   1937 │   │   │   │   │   │   │   │   dtype=self.dtype,                     │
│   1938 │   │   │   │   │   │   │   │   device=torch.cuda.current_device())   │
│   1939 │   │   │   self.ipg_buffer.append(buf_0)                             │
╰──────────────────────────────────────────────────────────────────────────────╯
RuntimeError: CUDA out of memory. Tried to allocate 954.00 MiB (GPU 0; 31.75 GiB
total capacity; 29.99 GiB already allocated; 445.94 MiB free; 30.27 GiB reserved
in total by PyTorch) If reserved memory is >> allocated memory try setting 
max_split_size_mb to avoid fragmentation.  See documentation for Memory 
Management and PYTORCH_CUDA_ALLOC_CONF

**Comment by LouisCastricato** [comment]
Hi please edit your comment and format your error correctly.

**Comment by LouisCastricato** [comment]
Also, Duy posted a solution. Please verify that it works. We can confirm on this example on our cluster we are unable to reproduce the OOM issue. I am under the impression that our learning to summarize code was trained on 80GB A100s, however I'm sure you could get it working on 40GB with minimal effort.

**Comment by JudeLee19** [comment]
Thank you for your reply. 
1) I've also tried with  cuda:1 for the reward model **but faced an OOM error as well.** In this case, I've tried with below config file.
<img width="323" alt="image" src="https://user-images.githubusercontent.com/6652613/216741548-dbc48006-922a-4345-ba31-1edd4f26b170.png">

**Because, when I tried with "default_accelerate_config.yaml" file with 4 GPUs, I got the below error.**

<img width="859" alt="image" src="https://user-images.githubusercontent.com/6652613/216740994-83399ad3-38a0-4c7e-a268-58cb5467b79d.png">

I guess it's related to the "default_accelerate_config.yaml" file. 

Here's my "default_accelerate_config.yaml" file.
```
command_file: null
commands: null
compute_environment: LOCAL_MACHINE
deepspeed_config:
  deepspeed_config_file: configs/ds_config_trlx_gptj_summarize.json
  zero3_init_flag: false
distributed_type: DEEPSPEED
downcast_bf16: 'no'
dynamo_backend: 'NO'
fsdp_config: {}
gpu_ids: null
machine_rank: 0
main_process_ip: null
main_process_port: null
main_training_function: main
megatron_lm_config: {}
mixed_precision: 'no'
num_machines: 1
**num_processes: 4**  I've tried with 4 GPUs.
rdzv_backend: static
same_network: true
tpu_name: null
tpu_zone: null
use_cpu: false

```

I have some follow-up questions.
1) How many GPUs have you tried on your machine?
2) can you share your "default_accelerate_config.yaml" file?

Thank you.

**Comment by PhungVanDuy** [comment]
> Thank you for your reply.
> 
> 1. I've also tried with  cuda:1 for the reward model **but faced an OOM error as well.** In this case, I've tried with below config file.
> 
> <img alt="image" width="323" src="https://user-images.githubusercontent.com/6652613/216741548-dbc48006-922a-4345-ba31-1edd4f26b170.png">
> 
> **Because, when I tried with "default_accelerate_config.yaml" file (I didn't change anything but num_processes to 4) with 4 GPUs, I got the below error.**
> 
> <img alt="image" width="859" src="https://user-images.githubusercontent.com/6652613/216740994-83399ad3-38a0-4c7e-a268-58cb5467b79d.png">
> 
> I guess it's related to the "default_accelerate_config.yaml" file.
> 
> Here's my "default_accelerate_config.yaml" file.
> 
> ```
> command_file: null
> commands: null
> compute_environment: LOCAL_MACHINE
> deepspeed_config:
>   deepspeed_config_file: configs/ds_config_trlx_gptj_summarize.json
>   zero3_init_flag: false
> distributed_type: DEEPSPEED
> downcast_bf16: 'no'
> dynamo_backend: 'NO'
> fsdp_config: {}
> gpu_ids: null
> machine_rank: 0
> main_process_ip: null
> main_process_port: null
> main_training_function: main
> megatron_lm_config: {}
> mixed_precision: 'no'
> num_machines: 1
> num_processes: 4  I've tried with 4 GPUs.
> rdzv_backend: static
> same_network: true
> tpu_name: null
> tpu_zone: null
> use_cpu: false
> ```
> 
> I have some follow-up questions.
> 
> 1. How many GPUs have you tried on your machine?
> 2. can you share your "default_accelerate_config.yaml" file?
> 
> Thank you.

I think I found the problem, please set `num_processes` equal to 1. The current code base does not support large reward model on multi-gpus if you want to run on multi-GPU, I recommend you write triton inference. We also shared default configuration here: `https://github.com/CarperAI/trlx/tree/main/examples/summarize_rlhf/configs` 

P/S: This model still able to work with 40GB.

**Comment by JudeLee19** [comment]
Oh, I see!! 

Thank you. I'll be working on running on multi-GPU in the future. 

Thank you :)

**Comment by xwwwwww** [comment]
Hi! @PhungVanDuy 
As I notice in #286, @LouisCastricato says he conducts PPO training with 8 to 32 GPUs.
Therefore, I would like to double check if the current version of trlx supports multi-GPU for ppo training.

**Comment by PhungVanDuy** [comment]
> 

Yes basically you can train PPO on multi-GPU but with the current code for summarization, we do not handle large reward model (GPT-J), if you use multi-GPUs for PPO and at one time PPO-process queries to large reward model it will induce OOM. That is why I mentioned that if you want to train on multi-GPU you should separate the reward model as an API (suggested use triton) to handle the queries from the PPO process. Our team also have code to use triton it will add on next release.

**Comment by xwwwwww** [comment]
Thanks for your quick reply, fully understood :)

I will try to build an API for the reward model with triton. And may I ask when your next release will be?

**Comment by PhungVanDuy** [comment]
> Thanks for your quick reply, fully understood :)
> 
> I will try to build an API for the reward model with triton. And may I ask when your next release will be?

That would be great if you can play with triton. I cannot say exactly when is next 0.5 release, It also depends on another PR going but we have planned for the end of this week or next week.

**Comment by JudeLee19** [comment]
@PhungVanDuy Thank you for the reference. I have one more question for you. 

Currently, I succeed in PPO training the 6B GPT model using one GPU with ur code but failed to train more big models (over 10B) on only one GPU. Would you give me a recommendation If I want to train the big models with multiple GPUs? (FYI, I have 8 A100 GPUs).

**Comment by PhungVanDuy** [comment]
> @PhungVanDuy Thank you for the reference. I have one more question for you.
> 
> Currently, I succeed in PPO training the 6B GPT model using one GPU with ur code but failed to train more big models (over 10B) with OOM on only one GPU. Would you give me some advice If I want to train the big models with multiple GPUs? (FYI, I have 8 A100 GPUs).

Did you try to use the offload CPU? I am going to train Pythia 12B, will let you know then if it works well.

**Comment by JudeLee19** [comment]
@PhungVanDuy Yes, I've tried with the below code to load over the 20B model.
```
self.base_model = transformers.AutoModelForCausalLM.from_pretrained(config,
                                                                                device_map="auto",
                                                                                offload_folder="offload",
                                                                                offload_state_dict=True)
```

Thanks.

**Comment by JudeLee19** [comment]
But didn't work out :(

**Comment by PhungVanDuy** [comment]
I haven't tried with the 20B model, what is your discord maybe we better to chat? My discord: daica#3877
