### ISSUE TITLE
Cuda OOM with PPO  on GPT2-medium

### ISSUE THREAD

**Issue by OleksandrKorovii** [CarperAI/trlx#372]
### 🐛 Describe the bug

I try to train `microsoft/DialoGPT-medium` with trlx. I have 2xRTX3090Ti. No matter what I do, I get `cuda out of memory`. For the reward model, I used fine-tuned my data sts-roberta-base. I tried to decrease `batch_size=2` and left unfreeze the last 2 layers, but it does not help. 
But when I fine-tuned dialoGPT-medium like the casual model on my setup I could put batch_size=10 with seq_len=1024. 

My train pipeline is familiar with examples `ppo-sentiments.py`. I used next following config: 

```
config = TRLConfig(
        train=TrainConfig(
            seq_length=256,
            epochs=5,
            total_steps=10000,
            batch_size=32,
            checkpoint_interval=10000,
            eval_interval=100,
            pipeline="PromptPipeline",
            trainer="AcceleratePPOTrainer",
        ),
        model=ModelConfig(model_path="microsoft/DialoGPT-medium", num_layers_unfrozen=2),
        tokenizer=TokenizerConfig(tokenizer_path="microsoft/DialoGPT-medium", truncation_side="right"),
        optimizer=OptimizerConfig(
            name="adamw", kwargs=dict(lr=1.0e-4, betas=(0.9, 0.95), eps=1.0e-8, weight_decay=1.0e-6)
        ),
        scheduler=SchedulerConfig(name="cosine_annealing", kwargs=dict(T_max=10000, eta_min=1.0e-4)),
        method=PPOConfig(
            name="PPOConfig",
            num_rollouts=128,
            chunk_size=128,
            ppo_epochs=1,
            init_kl_coef=0.05,
            target=6,
            horizon=10000,
            gamma=1,
            lam=0.95,
            cliprange=0.2,
            cliprange_value=0.2,
            vf_coef=1,
            scale_reward="ignored",
            ref_mean=None,
            ref_std=None,
            cliprange_reward=10,
            gen_kwargs=dict(
                max_new_tokens=120,
                top_k=0,
                top_p=1.0,
                do_sample=True,
            ),
        ),
    )

```

Maybe someone can help me with the configuration of the config, and how to run `DialoGPT-medium` with ppo on 2xRTX3090Ti?

### Which trlX version are you using?

`trlx==0.5.0`

### Additional system and package information

- `Accelerate` version: 0.15.0 - Platform: Linux-5.15.0-67-generic-x86_64-with-glibc2.35 - Python version: 3.10.6 - Numpy version: 1.24.1 - PyTorch version (GPU?): 1.13.1+cu117 (True) - `Accelerate` default config: 	- compute_environment: LOCAL_MACHINE 	- distributed_type: DEEPSPEED 	- mixed_precision: bf16 	- use_cpu: False 	- dynamo_backend: NO 	- num_processes: 2 	- machine_rank: 0 	- num_machines: 1 	- gpu_ids: None 	- main_process_ip: None 	- main_process_port: None 	- rdzv_backend: static 	- same_network: True 	- main_training_function: main 	- deepspeed_config: {'gradient_accumulation_steps': 1, 'offload_optimizer_device': 'cpu', 'offload_param_device': 'cpu', 'zero3_init_flag': False, 'zero_stage': 2} 	- fsdp_config: {} 	- megatron_lm_config: {} 	- downcast_bf16: no 	- tpu_name: None 	- tpu_zone: None 	- command_file: None 	- commands: None

**Comment by reciprocated** [comment]
@OleksandrKorovii Hey, I am able to run your config plugged into `ppo_sentiments.py` on a single 3090 while allocating only 18GB of memory. Even with that, you can reduce your memory usage by lowering `chunk_size`, which doesn't impact anything algorithmically, except the speed at which rollouts are collected. By doing that, the training allocates only 8GB.

Script (config with  minimal `chunk_size`) and launch command I used: https://gist.github.com/reciprocated/a2b9d441c11d8ca0c6eb8db591d630cc
Memory usage of two runs: https://wandb.ai/sorry/trlx/reports/Cuda-OOM-with-PPO-on-GPT2-medium-372---VmlldzozODUxMzYy
 
Since I can't reproduce OOM here on this setup, could you retry your runs, maybe with modifications I've suggested, and post your w&b run here? 🙏

**Comment by dsh54054** [comment]
> @OleksandrKorovii Hey, I am able to run your config plugged into `ppo_sentiments.py` on a single 3090 while allocating only 18GB of memory. Even with that, you can reduce your memory usage by lowering `chunk_size`, which doesn't impact anything algorithmically, except the speed at which rollouts are collected. By doing that, the training allocates only 8GB.
> 
> Script (config with minimal `chunk_size`) and launch command I used: https://gist.github.com/reciprocated/a2b9d441c11d8ca0c6eb8db591d630cc Memory usage of two runs: https://wandb.ai/sorry/trlx/reports/Cuda-OOM-with-PPO-on-GPT2-medium-372---VmlldzozODUxMzYy
> 
> Since I can't reproduce OOM here on this setup, could you retry your runs, maybe with modifications I've suggested, and post your w&b run here? 🙏

hey, the link (https://gist.github.com/reciprocated/a2b9d441c11d8ca0c6eb8db591d630cc) you provided seems to be invalid, Can you provide me with the configuration script again？

**Comment by OleksandrKorovii** [comment]
@reciprocated Yeah, everything works now.  It will be good if you create the docs for other people, which parameters in the config have an influence on VRAM.

**Comment by reciprocated** [comment]
@dsh54054 Hey, that link doesn't seem to be invalid for me (and it's not private), do you mean you cannot access `gist.github.com` subdomain or perhaps that you're having issues with the script itself?

@OleksandrKorovii Great! And I will update docs with that information
